language: cpp

os:
  - windows
  - linux

addons:
  apt:
    packages:
      - cmake
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - mesa-common-dev

script:
  - cmake .
  - cmake --build .